### ISSUE TITLE
Removal of `DiskObjectStore.move_in_pack()` broke hg-git

### ISSUE THREAD

**Issue by danchr** [jelmer/dulwich#1139]
The `move_in_pack()` in `DiskObjectStore` was removed in commit 5e79204349d5. This broke hg-git, which uses it as an optimitisation on the initial clone, where moving in the temporary file is always safe.

Would you perhaps consider reinstating this method?

**Comment by jelmer** [comment]
On Fri, Jan 27, 2023 at 06:55:36AM -0800, Dan Villiom Podlaski Christiansen wrote:
> The `move_in_pack()` in `DiskObjectStore` was removed in commit 5e79204349d5. This broke hg-git, which uses it as an optimitisation on the initial clone, where moving in the temporary file is always safe.
> 
> Would you perhaps consider reinstating this method?

You should be able to call _move_in_pack() instead. I guess we could make that
public again, perhaps making the file object argument optional (and having the
function open the file if not specified).

**Comment by danchr** [comment]
Well, you did remove the function entirely in #1130 :slightly_smiling_face:

Anyway, it seems that the way hg-git _should_ be doing this is by using `add_pack()`. That works fine for 0.21, but I get some rather weird errors with 0.20.50; there's a `KeyError` out of the blue in `_ensure_no_pending()`. Could that be caused by thin packs?

**Comment by jelmer** [comment]
Oops, I'd forgotten about that and was looking at an old version of Dulwch (-:

.add_pack() is indeed the right thing to call, but like you say - older incarnations of it didn't handle thin packs well. That's part of the cleanups that have happened. Although the old .move_in_pack() was not meant to be used with thin packs either - since it didn't do any verification it would happily add thin packs to your object store.

So I think it would probably make sense to add a convenience wrapper "move_in_pack(self, path)" back.
