### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by mitsuhiko** [jelmer/dulwich#153]
The fact that dulwich is currently GPL licensed removes a lot of usefulness of the project as a storage format for other things.  Are there any chances that the license could change to something like BSD?

**Comment by tony** [comment]
@jelmer Why did you gpl this?  Is it incorporating LGPL/GPL code?

MIT / BSD / Apache open source projects can't use this project, it'd trigger a derivative.

I emailed the PSF on this - and the conversations eventually came down to "We don't know how (L)GPL effects X" - it's never been tested in court.

If your intention is for this python library to be viral, that's ok, but you're not gaining anything, just losing a lot. :smile:

**Comment by tony** [comment]
> Yeah, I'm hoping to relicense it under Apachev2 (+ GPLv2, for compatibility). I
sent out emails a while ago to all contributors asking if they were okay with
relicensing. Not everybody replied (those who did were happy with changing the
license). I have not had time to follow up with those who did not respond.

Sorry, I missed the above.

You could make a statement / ``contributing.md`` that further code contribution will be licensed Apache 2 - so the backlog doesn't pile up.

See what Neovim did: https://github.com/neovim/neovim#license

**Comment by jelmer** [comment]
On Tue, May 19, 2015 at 09:13:25PM -0700, Tony Narlock wrote:
> > Yeah, I'm hoping to relicense it under Apachev2 (+ GPLv2, for compatibility). I
> sent out emails a while ago to all contributors asking if they were okay with
> relicensing. Not everybody replied (those who did were happy with changing the
> license). I have not had time to follow up with those who did not respond.
> 
> Sorry, I missed the above.
This is still the plan, though it hasn't really been priority for me -
concrete examples of MIT/Apache2-licensed projects that are blocked
from using Dulwich because of the license would help with
priorization. :-)

> You could make a statement / ``contributing.md`` that further code contribution will be licensed Apache 2 - so the backlog doesn't pile up.
> 
> See what Neovim did: https://github.com/neovim/neovim#license
That's a good idea. I'll see if I can add do something similar for
GPL+Apache2 in Dulwich.

Cheers,

Jelmer

-- 
Jelmer Vernooij <jelmer@samba.org> - https://jelmer.uk/

**Comment by jelmer** [comment]
I've added a text doc with the current status - see https://github.com/jelmer/dulwich/blob/master/relicensing-apachev2.txt

Just to reiterate; the main thing that would help me prioritize this issue is examples of /FOSS/ projects that are being prevented from using Dulwich for licensing reasons.

**Comment by jonashaag** [comment]
http://github.com/jonashaag/klaus, currently BSD-licensed

**Comment by jelmer** [comment]
I've sent out an e-mail about this, CCed to all contributors with code that is GPLv2-only; see https://lists.launchpad.net/dulwich-users/msg00836.html

**Comment by jelmer** [comment]
@michael-k @max0d41 @lukaszb @rsalveti @svilain @samv @kwatters @davidblewett Please have a look at https://github.com/jelmer/dulwich/blob/master/relicensing-apachev2.txt

**Comment by jelmer** [comment]
Now down to 10 people I still need to hear from..

**Comment by jelmer** [comment]
ping @eberle1080 @garyvdm @vtjnash @max0d41 @warrd @damz

**Comment by jelmer** [comment]
Down to the last 6 contributors I haven't heard back from now; just sent out another e-mail.

**Comment by max0d41** [comment]
I'm okay with this relicensing.

**Comment by jelmer** [comment]
@garyvdm ping

**Comment by insertinterestingnamehere** [comment]
@garyvdm?

**Comment by jonashaag** [comment]
@insertinterestingnamehere He's already relicensed. The only people left over are

Artem Tikhomirov (1 contribution)
Risto Kankkunen (14 contributions)

**Comment by jelmer** [comment]
On Thu, Mar 10, 2016 at 11:55:17PM -0800, Jonas Haag wrote:
> @insertinterestingnamehere He's already relicensed. The only people left over are
> 
> Artem Tikhomirov (1 contribution)
> Risto Kankkunen (14 contributions)

I've had trouble reaching both of them repeatedly, both at the
addresses I already had and at their companies. If anybody can reach
out to them, that would be great.

**Comment by jonashaag** [comment]
I already thought about just getting rid of their contributions and coding them up again, but that would be quite some work for Risto I guess

**Comment by tony** [comment]
@jelmer @jonashaag in the mean time, can you change the license for contributions from here on are MIT licensed.

**Comment by tony** [comment]
I'm not sure I see the point of GPLv2 and Apache at the same time, if you used MIT, it would be forward compatible with both of them.

I added a PR to clarify the language that commits are dual licensed.  The language in ``relicensing-apachev2.txt`` isn't clear enough.

**Comment by jelmer** [comment]
Already done. See the copying file.

On 3 June 2016 03:36:25 CEST, Tony Narlock <notifications@github.com> wrote:
>@jelmer @jonashaag in the mean time, can you change the license for
>contributions from here on are MIT licensed.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/153#issuecomment-223469607

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jelmer** [comment]
MIT doesn't have any patent provisions, which is why I prefer Apache2.



On 3 June 2016 03:55:36 CEST, Tony Narlock <notifications@github.com> wrote:
>I'm not sure I see the point of GPLv2 and Apache at the same time, if
>you used MIT, it would be forward compatible with both of them.
>
>I added a PR to clarify the language that commits are dual licensed. 
>The language in ``relicensing-apachev2.txt`` isn't clear enough.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/153#issuecomment-223472019

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tony** [comment]
you could MIT + Patent Exception (https://github.com/dotnet/coreclr/blob/master/PATENTS.TXT) and not create ambiguity with two licenses at once.

only see GPL in COPYING. https://github.com/jelmer/dulwich/blob/master/COPYING

I made an issue in #432

**Comment by jelmer** [comment]
I don't see a problem with dual licencing, and think it's clearer that using MIT with an additional restriction.

On 3 June 2016 16:49:14 CEST, Tony Narlock <notifications@github.com> wrote:
>you could MIT + Patent Exception
>(https://github.com/dotnet/coreclr/blob/master/PATENTS.TXT) and not
>create ambiguity with two licenses at once.
>
>only see GPL in COPYING.
>https://github.com/jelmer/dulwich/blob/master/COPYING
>
>I made an issue in #432
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/153#issuecomment-223599855

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tony** [comment]
MIT is forward compatible to both Apache and GPL.  If the user were given
the choice to pick either, none of the terms of Apache/GPL have same effect
in the end. The user still has to contribute back under a dual-license, and
someone who didn’t want to contribute could simply use Apache2.

So it adds two licenses more complex than MIT, while also giving the
copyleft no teeth, there are no binary blobs in a pure python
implementation of git, libs are also always (in practice) distributed with
source. The redundancy / contradiction of this also confuses people to what
the project’s intentions are.

jQuery used to dual-license MIT and GPL. It confused many people:

https://blog.jquery.com/2012/09/10/jquery-licensing-changes/

Here’s an issue of someone being confused over it:
https://programmers.stackexchange.com/questions/139663/confusion-about-dual-license-mit-gpl-javascript-for-use-on-my-website

In any event, I’m closing my PR at #432 and moving on to other things for
the moment. I don’t want to cause confusion for other devs. :smile:

On June 3, 2016 at 11:59:38 AM, Jelmer Vernooij (notifications@github.com)
wrote:

I don't see a problem with dual licencing, and think it's clearer that
using MIT with an additional restriction.

On 3 June 2016 16:49:14 CEST, Tony Narlock <notifications@github.com> wrote:
>you could MIT + Patent Exception
>(https://github.com/dotnet/coreclr/blob/master/PATENTS.TXT) and not
>create ambiguity with two licenses at once.
>
>only see GPL in COPYING.
>https://github.com/jelmer/dulwich/blob/master/COPYING
>
>I made an issue in #432
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jelmer/dulwich/issues/153#issuecomment-223599855

--
Sent from my Android device with K-9 Mail. Please excuse my brevity.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jelmer/dulwich/issues/153#issuecomment-223634364>, or mute
the thread
<https://github.com/notifications/unsubscribe/AABm4KRsLjs2NxWsNEiTkrJ0oDVxrbwxks5qIF15gaJpZM4Bs-xs>
.

**Comment by jelmer** [comment]
MIT with additional restrictions is not the same thing as plain MIT, it's creating yet another license - and that would confuse people too. Apachev2 and GPLv2 are standard licenses; it's well known what they are compatible with. 

On a more practical side, the people who contributed to Dulwich that I had to contact specifically gave permission to relicense as their contribution under the Apachev2 license. I don't want to contact everybody again; this whole process took almost two years.

**Comment by jelmer** [comment]
Only one commit left licensed under solely GNU GPLv2 or later: https://jelmer.uk/code/dulwich/commit/c1787f51f4eb03a5a4d56d5a34429ae7639d2093/

**Comment by jelmer** [comment]
I have confirmation from Syntevo now, so everybody has agreed to relicensing under dual Apachev2+/GPLv2+.

I'll update the license in the repo in the next week or so. Thanks to everybody for their patience. 

Contacting all contributors about the license was tedious and took a long time. I'm glad we managed to get it done.

**Comment by jelmer** [comment]
I've pushed updates to COPYING, setup.py, CONTRIBUTING.md, etc mentioning the new license. Only thing left to do now is to update all the file headers.

**Comment by jelmer** [comment]
Updated the preambles.Closing bug :)
