### ISSUE TITLE
Documentation for Repo.path attribute

### ISSUE THREAD

**Issue by traits** [jelmer/dulwich#854]
Hi,

I was looking for a way to get a local repositories root directory from a python source inside this repository. I can discover the repository with 'discover', but there is no documentation (or I was unable to find it) for the 'path' attribute, eventually holding the information in question. 

Related to this, as a long-time git user the terms 'control directory' and 'common directory' are not quite self-explanatory to me. Some short remark in the documentation would make this clear.

**Comment by jelmer** [comment]
On Thu, Mar 18, 2021 at 06:10:50PM -0700, Michael wrote:
> @all 
> 
> I was looking for a way to get a local repositories root directory from a python source inside this repository. I can discover the repository with 'discover', but there is no documentation (or I was unable to find it) for the 'path' attribute, eventually holding the information in question. 
> 
> Related to this, as a long-time git user the terms 'control directory' and 'common directory' are not quite self-explanatory to me. Some short remark in the documentation would make this clear. 

"common directory" is a term used by git itself as well - see e.g. the
GIT_COMMON_DIR variable in git(1). The "control directory" is what is
commonly referred to as "git directory" in Git itself.

"path" is set to the top-level directory for the repository - i.e. the
.git directory for a bare repository and the working directory
otherwise.

A pull request to improve the docs would be great.

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc
